### ISSUE TITLE
Support UTF-8 on Accumulate Explorer.

### ISSUE THREAD

**Issue by operatecrypto** [AccumulateNetwork/explorer#80]
Currently the explorer does not display the data in UTF-8 format. It will be benficial to add such a feature

**Comment by firelizzard18** [comment]
From Discord:

> This is the sample data https://kermit.explorer.accumulatenetwork.io/data/0060e21e5fd2e5a008ef6628954dcec1b69ed46217e8146fd7b4846c5cb71211@augtest8.acme/test/test2/discoveryV1ClientDefault_socialprofile/Info_V1

> This data appears to be UTF-16 instead of UTF-8. There are too many possible encodings to support all of them and given that UTF-8 is used more widely than any of the others (plus UTF-16 comes in two different 'flavors') I'm inclined to only support UTF-8.

**Comment by firelizzard18** [comment]
Here is an example with some arbitrary Chinese text: https://kermit.explorer.accumulatenetwork.io/tx/ba99a966ea31ab7a95b5410ce87a06efa52f5e2392183dde331e231b091b7706
